apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-webapi
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: dotnet-webapi
          image: task0209/chillapp:v1
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
